version: '3'
services:
  flask_app:
    container_name: flask_app_backend
    build: ./flask_backend
    volumes:
      - ./flask_backend:/flask_backend
    ports:
      - '5000:5000'
    env_file:
      - ./flask_backend/.env
    working_dir: /flask_backend

  react_app:
    container_name: react_frontend
    env_file: './twilio_react_app/.env'
    build:
      context: ./twilio_react_app
      dockerfile: ./Dockerfile
    image: 'front_end'
    ports:
      - '3000:3000'
